apiVersion: v2
name: ruan
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0
icon: https://logodownload.org/wp-content/uploads/2018/03/nginx-logo-1.png
dependencies:
- name: chart-common
  version: "0.1.0"
  condition: chart-common.enabled
  repository: "file://../commons/chart-common"